@Person_HostAddress = http://localhost:5051

//GET {{Person_HostAddress}}/weatherforecast/
//Accept: application/json

###

GET {{Person_HostAddress}}/person/
Accept: application/json

###
POST {{Person_HostAddress}}/person/
Content-Type: application/json

{
  "name": "John Doe"
}
###

PUT {{Person_HostAddress}}/person/21d0aab2-e6f8-4b53-bce3-c93c925c7665
Content-Type: application/json

{
  "name": "Micaele Veracustia"
}

###
DELETE {{Person_HostAddress}}/person/21d0aab2-e6f8-4b53-bce3-c93c925c7665
Content-Type: application/json

{
  "name": "Micaele Veracustia"
}

